Jai Babe Di
Jai Guru Maa Ji
---
title: "R Notebook"
output: html_notebook
---

```{r}
library(nanostringr)
library(ComplexHeatmap)
library(dplyr)
library(ggplot2)
library(circlize)
library(DESeq2)
library(readxl)
library(reshape2)
library(msigdbr)
library(fgsea)
library(enrichplot)
set.seed(1234)
setwd("~/Desktop/Nanostring_mRNA_project/")
```

```{r}
liver_matx <- readRDS("~/Desktop/Nanostring_mRNA_project/output_files/liver_GSEA_grp2_data.rds")
```

```{r}
gene1 <- liver_matx[liver_matx$pvalue <0.05,]$core_enrichment[1]
```


```{r}
x2 <- read.csv("~/Desktop/Nanostring_mRNA_project/output_files/normalized_liver_data.csv", check.names = FALSE)
rownames(x2)<- c(x2[1])[[1]]
x2 <- x2[-1]
```


```{r}
library(readxl)
liver_meta_data <- read_excel("~/Library/CloudStorage/OneDrive-NationalInstitutesofHealth/Work/Nanostring_data/NATanalysis1.xlsx",sheet = "LIVER")
liver_meta_data$`File name`<- toupper(liver_meta_data$`File name`)
liver_meta_data <- liver_meta_data[liver_meta_data$`File name` %in% colnames(x2),]
```

```{r}
# Create a data frame for the annotations
sample_order <- match(colnames(x2), liver_meta_data$`File name`)
metadata_ordered <- liver_meta_data[sample_order, ]

annotations <- data.frame(
  GROUPS_1 = metadata_ordered$GROUPS_1,
  GROUPS_2 = metadata_ordered$GROUPS_2,
  row.names = metadata_ordered$`File name`
)

```


```{r}
# Create the heatmap annotations
ha <- rowAnnotation(
  GROUPS_1 = annotations$GROUPS_1,
  GROUPS_2 = annotations$GROUPS_2,
  col = list(
    GROUPS_1 = c("1" = "#D6604D", "2" = "#009999", "3" = "#4393C3"),
    GROUPS_2 = c("1a" = "#F4A582","1b" = "#FDDBC7","2" = "#009999", "3a" = "#D1E5F0","3b" ="#92C5DE")
  )
)

# Define custom colors for the heatmap
heatmap_colors <- colorRamp2(c(-3, 0, 3), rev(RColorBrewer::brewer.pal(11, "RdBu")[c(2, 6, 11)]))
```



```{r}
liver_marker <- c("ALB", "APOE", "CDH2","ORM1", "ESR2", "FOXO3","SRY")
HOXD10, SLC13A2, OSM, MMP3, CXCL6, and CXCL8 
# selective genes
bone <- c("IL11", "MMP1", "CTGF", "CXCR4","OPN")

x2[c("PPP1R1B", "PREX1", "IGF2BP1"),]

x2[c("ABCC1", "ABCC3", "ABCC4","SLC22A1", "ABCC10"),]
na.omit(x2[c("VEGFA", "EGFR", "MYOM2", "GNGT1", "C3", "MUC1", "IGF2", "GLI1", "GNG12", "GRIA1", "IHH", "VCAM1","GPC3"),])
```


```{r}

# Create and draw the heatmap
Heatmap(
  scale(t(na.omit(x2[c("VEGFA", "EGFR", "MYOM2", "GNGT1", "C3", "MUC1", "IGF2", "GLI1", "GNG12", "GRIA1", "IHH", "VCAM1","GPC3"),]))),
  name = "Expression",
  left_annotation = ha,
  show_row_names = TRUE,
  show_column_names = TRUE,
  col = heatmap_colors,
  cluster_rows = TRUE,
  cluster_columns = TRUE,
  show_column_dend = FALSE,
  show_row_dend = FALSE,
  #show_parent_dend_line = FALSE,
  row_title_gp = gpar(fontsize = 14,fontface = "bold"),
  column_title_gp = gpar(fontsize = 14,  fontface = "bold"),
#  column_names_gp = gpar(fontsize = 6, angle = 90, vjust = 1, hjust = 1),
  row_names_gp = gpar(fontsize = 12, fontface = "bold"),
  row_split = annotations$GROUPS_1,
  row_title = "Sample ID"
)
```

