Jai Babe Di
Jai Guru Maa Ji
---
title: "R Notebook"
output: html_notebook
---

```{r}
library(nanostringr)
library(ComplexHeatmap)
library(dplyr)
library(ggplot2)
library(circlize)
library(DESeq2)
library(readxl)
library(reshape2)
set.seed(1234)
setwd("~/Desktop/Nanostring_mRNA_project/")
```

```{r}
# read the RCC files
data <- read_rcc("~/Desktop/Nanostring_mRNA_project/lung/")

# posivite control normalization
  raw_exprs <- data$raw
  gm <- exp(colMeans(log(raw_exprs[raw_exprs$Code.Class == "Positive",4:dim(raw_exprs)[2]]), na.rm = T))
  am <- mean(gm, na.rm = T)
  sf1 <- sapply(gm, function(y) am/y)
  raw_exprs <- as.matrix(raw_exprs[,4:dim(raw_exprs)[2]])
  raw_exprs1 <- sapply(1:ncol(raw_exprs), function(i) sf1[i] * as.numeric(raw_exprs[,i]))
 
# housekeeping normalization
  raw_exprs <- data$raw
  gm <- exp(colMeans(log(raw_exprs[raw_exprs$Code.Class == "Housekeeping",4:dim(raw_exprs)[2]]), na.rm = T))
  am <- mean(gm, na.rm = T)
  sf2 <- sapply(gm, function(y) am/y)
# use positive cont normalized matrix
  raw_exprs2 <- sapply(1:ncol(raw_exprs1), function(i) sf2[i] * as.numeric(raw_exprs1[,i]))
# col and rowname  
  rownames(raw_exprs2) <- raw_exprs$Name
  colnames(raw_exprs2) <- colnames(raw_exprs)[4:dim(raw_exprs)[2]]
  # use only endogenous
  raw_exprs2 <- raw_exprs2[raw_exprs$Code.Class == "Endogenous",]
  x2 <- raw_exprs2[,!is.na(sf2) & !is.infinite(sf2)]
#modify colname
colnames(x2) <- gsub("20240628_CS036765 Mazcko[0-9] 062724_|20240617_CS036764 Mazcko[0-9] 061724_|20240627_CS036765 Mazcko[0-9] 062724_", "", colnames(x2))
colnames(x2) <- gsub("_[0-9]+$", "", colnames(x2))
colnames(x2)<- gsub("\ $", "", colnames(x2))
colnames(x2) <- toupper(colnames(x2))
# samples excluded
sf2[is.infinite(sf2)]
write.csv(x2,"~/Desktop/Nanostring_mRNA_project/output_files/normalized_lung_data.csv")
```


