Jai Babe Di
Jai Guru Maa Ji
---
title: "R Notebook"
output: html_notebook
---


```{r}
library(nanostringr)
library(ComplexHeatmap)
library(dplyr)
library(ggplot2)
library(circlize)
library(DESeq2)
library(readxl)
library(reshape2)
library(stringr)
set.seed(1234)
setwd("~/Desktop/Nanostring_mRNA_project/")
```

```{r}
x2 <- read.csv("~/Desktop/Nanostring_mRNA_project/output_files/normalized_kidney_data.csv", check.names = FALSE)

rownames(x2)<- c(x2[1])[[1]]
x2 <- x2[-1]
colnames(x2) <- str_replace_all(colnames(x2),"\\s+","_")
```


```{r}
meta_data <- read_excel("~/Desktop/Nanostring_mRNA_project/NATanalysis1_29july.xlsx",sheet = "KIDNEY")
meta_data$`File name`<- toupper(meta_data$`File name`)
meta_data$`File name` <- str_replace_all(meta_data$`File name`,"\\s+","_")
meta_data <- meta_data[meta_data$`File name` %in% colnames(x2),]
meta_data <- meta_data[meta_data$PAIR...8 %in% c(1,2),]
# select only paris
x2 <- x2[,c(meta_data$`File name`)]
```

```{r}
# Create a data frame for the annotations
sample_order <- match(colnames(x2), meta_data$`File name`)
metadata_ordered <- meta_data[sample_order, ]

annotations <- data.frame(
  GROUPS_1 = metadata_ordered$PAIR...8,
  row.names = metadata_ordered$`File name`
)

```


```{r}
# Create the heatmap annotations
ha <- rowAnnotation(
  GROUPS_1 = annotations$GROUPS_1,
  col = list(
    GROUPS_1 = c("1" = "#D6604D", "2" = "#009999", "3" = "#4393C3")
  )
)

# Define custom colors for the heatmap
heatmap_colors <- colorRamp2(c(-2, 0, 2), rev(RColorBrewer::brewer.pal(11, "RdBu")[c(2, 6, 11)]))


pdf("~/Desktop/Nanostring_mRNA_project/Plots/kidney_expression_heatmap1.pdf", height = 4, width = 8)

# Create and draw the heatmap
Heatmap(
  scale(t(x2)),
  name = "Expression",
  left_annotation = ha,
  show_row_names = TRUE,
  show_column_names = FALSE,
  #col = heatmap_colors,
  cluster_rows = TRUE,
  cluster_columns = TRUE,
  show_column_dend = FALSE,
  show_row_dend = FALSE,
  #show_parent_dend_line = FALSE,
  row_title_gp = gpar(fontsize = 14,fontface = "bold"),
  column_title_gp = gpar(fontsize = 14,  fontface = "bold"),
#  column_names_gp = gpar(fontsize = 6, angle = 90, vjust = 1, hjust = 1),
  row_names_gp = gpar(fontsize = 12, fontface = "bold"),
  row_split = annotations$GROUPS_1,
  row_title = "Sample ID"
)
```


