Jai Babe Di
Jai Guru Maa Ji

---
title: "R Notebook"
output: html_notebook
---

```{r}
library(nanostringr)
library(ComplexHeatmap)
library(dplyr)
library(ggplot2)
library(circlize)
library(DESeq2)
library(readxl)
library(reshape2)
library(msigdbr)
library(fgsea)
library(clusterProfiler)
library(enrichplot)
set.seed(123456)
setwd("~/Desktop/Nanostring_mRNA_project/")
```



```{r}
x2 <- read.csv("~/Desktop/Nanostring_mRNA_project/output_files/normalized_kidney_data.csv", check.names = FALSE)
rownames(x2)<- c(x2[1])[[1]]
x2 <- x2[-1]
colnames(x2) <- str_replace_all(colnames(x2),"\\s+","_")
```



```{r}
# pathway for GROUP 2
meta_data <- read_excel("~/Desktop/Nanostring_mRNA_project/NATanalysis1_29july.xlsx",sheet = "KIDNEY")
meta_data$`File name`<- toupper(meta_data$`File name`)
meta_data<- as.data.frame(meta_data)
rownames(meta_data)<- meta_data$`File name`
meta_data$`File name` <- str_replace_all(meta_data$`File name`,"\\s+","_")

meta_data<- meta_data[!(is.na(meta_data$`PAIR (cortex/medulla)`) & is.na(meta_data$`PAIR (prox/distant)`)),]
meta_data <- meta_data[meta_data$`File name` %in% colnames(x2),]
```
```{r}
# remove entries include or not in x2 also
x2 <- x2[, colnames(x2) %in% meta_data$`File name`]
```

```{r}

# make combinations
comb1 <- c("Cortex","Medulla")

edit_list <- lapply(list(comb1), function(x){
#x<- comb1
meta_data <- meta_data[meta_data$`PAIR (cortex/medulla)` %in% x,]

##########################################
# expr matx
exp1 <- x2[,colnames(x2) %in% meta_data$`File name`]
# grouping 
grp1 <- as.factor(meta_data$`PAIR (cortex/medulla)`)
grp1 <- factor(grp1, levels = x)
grp1
# genes
gene1 <- rownames(x2)
#########################
counts.DGEList <- DGEList(counts = round(exp1), genes = gene1, group = grp1)
counts.keep <- filterByExpr(y = counts.DGEList)
counts.DGEList <- counts.DGEList[counts.keep, , keep.lib.sizes = FALSE]
#normalization of counts
counts.DGEList <- calcNormFactors(counts.DGEList, method = "upperquartile")
counts.DGEList$counts <- log2(cpm(counts.DGEList) + 1)
counts.DGEList <- estimateDisp(counts.DGEList,design = model.matrix(~grp1))
print(model.matrix(~grp1))
rest_treatment.DGEExact <- exactTest(counts.DGEList,dispersion=0.2)
########################
msigdbr_df <- msigdbr(species = "dog", category = "H")
msigdbr_list = split(x = msigdbr_df$gene_symbol, f = msigdbr_df$gs_name)
ranks1 <- rest_treatment.DGEExact$table$logFC
names(ranks1) <- counts.DGEList$genes$genes
ranks1 <- sort(ranks1, decreasing = T)
gsea_res1 <- GSEA(geneList = ranks1, TERM2GENE = subset(msigdbr_df, select = c("gs_name","gene_symbol")),
                  pvalueCutoff = 1)
fgseaResTidy <- gsea_res1 %>%
as_tibble() %>%
arrange(desc(NES))
fgseaResTidy$Treatment <- paste0(x[2]," Vs. ",x[1])
#######################
p1 <- ggplot(fgseaResTidy, aes(reorder(ID, NES), NES)) +
geom_col(aes(fill=p.adjust < 0.05)) +
coord_flip() + ggtitle("")+
labs(x="Pathway", y="Normalized Enrichment Score",title="") +  
theme_minimal() +
theme(axis.text.y = element_text(size = 12,angle = 0, vjust = 0.5, hjust = 1),
      axis.text.x = element_text(size =12, hjust = 1), text = element_text(size = 18, face = "bold"))+ 
 annotate("text", x = length(fgseaResTidy$ID), y = min(fgseaResTidy$NES)+0.4, label = x[2],fontface = "bold", size =8)+
annotate("text", x = 1, y = max(fgseaResTidy$NES)-0.3, label = x[1],fontface = "bold", size = 8)
ggsave(plot = p1,filename = "~/Desktop/Nanostring_mRNA_project/Plots/kidney_cort_med_combination_comp_padj.pdf", height = 8, width = 12, bg = "white")
plot(p1)

p2 <- ggplot(fgseaResTidy, aes(reorder(ID, NES), NES)) +
geom_col(aes(fill=pvalue < 0.05)) +
coord_flip() + ggtitle("")+
labs(x="Pathway", y="Normalized Enrichment Score",title="") +  
theme_minimal() +
theme(axis.text.y = element_text(size = 12,angle = 0, vjust = 0.5, hjust = 1),
      axis.text.x = element_text(size =12, hjust = 1), text = element_text(size = 18, face = "bold"))+ 
 annotate("text", x = length(fgseaResTidy$ID), y = min(fgseaResTidy$NES)+0.4, label = x[2],fontface = "bold", size =8)+
annotate("text", x = 1, y = max(fgseaResTidy$NES)-0.3, label = x[1],fontface = "bold", size = 8)
ggsave(plot = p2,filename = "~/Desktop/Nanostring_mRNA_project/Plots/kidney_cort_med_combination_comp_pval.pdf", height = 8, width = 12, bg = "white")
plot(p2)
return(fgseaResTidy)
})

```

```{r}
# make combinations
comb1 <- c("Distant","Adjacent")

edit_list2 <- lapply(list(comb1), function(x){
meta_data <- meta_data[meta_data$`PAIR (prox/distant)` %in% x,]

##########################################
# expr matx
exp1 <- x2[,colnames(x2) %in% meta_data$`File name`]
# grouping 
grp1 <- as.factor(meta_data$`PAIR (prox/distant)`)
grp1 <- factor(grp1, levels = x)
grp1
# genes
gene1 <- rownames(x2)
#########################
counts.DGEList <- DGEList(counts = round(exp1), genes = gene1, group = grp1)
counts.keep <- filterByExpr(y = counts.DGEList)
counts.DGEList <- counts.DGEList[counts.keep, , keep.lib.sizes = FALSE]
#normalization of counts
counts.DGEList <- calcNormFactors(counts.DGEList, method = "upperquartile")
counts.DGEList$counts <- log2(cpm(counts.DGEList) + 1)
counts.DGEList <- estimateDisp(counts.DGEList,design = model.matrix(~grp1))
print(model.matrix(~grp1))
rest_treatment.DGEExact <- exactTest(counts.DGEList,dispersion=0.2)
########################
msigdbr_df <- msigdbr(species = "dog", category = "H")
msigdbr_list = split(x = msigdbr_df$gene_symbol, f = msigdbr_df$gs_name)
ranks1 <- rest_treatment.DGEExact$table$logFC
names(ranks1) <- counts.DGEList$genes$genes
ranks1 <- sort(ranks1, decreasing = T)
gsea_res1 <- GSEA(geneList = ranks1, TERM2GENE = subset(msigdbr_df, select = c("gs_name","gene_symbol")),
                  pvalueCutoff = 1)
fgseaResTidy <- gsea_res1 %>%
as_tibble() %>%
arrange(desc(NES))
fgseaResTidy$Treatment <- paste0(x[2]," Vs. ",x[1])
#######################
p1 <- ggplot(fgseaResTidy, aes(reorder(ID, NES), NES)) +
geom_col(aes(fill=p.adjust < 0.05)) +
coord_flip() + ggtitle("")+
labs(x="Pathway", y="Normalized Enrichment Score",title="") +  
theme_minimal() +
theme(axis.text.y = element_text(size = 12,angle = 0, vjust = 0.5, hjust = 1),
      axis.text.x = element_text(size =12, hjust = 1), text = element_text(size = 18, face = "bold"))+ 
 annotate("text", x = length(fgseaResTidy$ID), y = min(fgseaResTidy$NES)+0.4, label = x[2],fontface = "bold", size =8)+
annotate("text", x = 1, y = max(fgseaResTidy$NES)-0.3, label = x[1],fontface = "bold", size = 8)
ggsave(plot = p1,filename = "~/Desktop/Nanostring_mRNA_project/Plots/kidney_dis_pro_combination_comp_pdj.pdf", height = 8, width = 12, bg = "white")
plot(p1)

p2 <- ggplot(fgseaResTidy, aes(reorder(ID, NES), NES)) +
geom_col(aes(fill=pvalue < 0.05)) +
coord_flip() + ggtitle("")+
labs(x="Pathway", y="Normalized Enrichment Score",title="") +  
theme_minimal() +
theme(axis.text.y = element_text(size = 12,angle = 0, vjust = 0.5, hjust = 1),
      axis.text.x = element_text(size =12, hjust = 1), text = element_text(size = 18, face = "bold"))+ 
 annotate("text", x = length(fgseaResTidy$ID), y = min(fgseaResTidy$NES)+0.4, label = x[2],fontface = "bold", size =8)+
annotate("text", x = 1, y = max(fgseaResTidy$NES)-0.3, label = x[1],fontface = "bold", size = 8)
ggsave(plot = p2,filename = "~/Desktop/Nanostring_mRNA_project/Plots/kidney_dis_pro_combination_comp_pval.pdf", height = 8, width = 12, bg = "white")
plot(p2)

return(fgseaResTidy)
})

```



```{r}
all_data <- do.call(rbind, c(edit_list,edit_list2))

path_ord1 <- all_data %>% 
  select(ID, Treatment, NES) %>% 
  spread(Treatment, NES) %>% 
  tibble::column_to_rownames("ID") %>% 
  data.matrix() %>% 
  # dist(method = "euclidean") %>% 
   #hclust("ward.D2")
  dist() %>% 
  hclust()
path_ord1 <- path_ord1$labels[path_ord1$order]
all_data <- all_data%>%
  mutate(NES = case_when(NES > 2 ~ 2,NES < -2 ~ -2, T ~ NES)) %>% 
 # mutate(ID = factor(ID, levels = path_ord1)) %>% 
   #mutate(Treatment = factor(Treatment, levels = c(
    # "Yes-met Vs. Control",   "No-met Vs. Control","Yes-met Vs. No-met"))) %>% 
  ungroup()
saveRDS(all_data,"~/Desktop/Nanostring_mRNA_project/output_files/kidney_paired_combination.rds")
```

```{r}
all_data <- readRDS("~/Desktop/Nanostring_mRNA_project/output_files/kidney_paired_combination.rds")
write.csv(all_data, "~/Desktop/Nanostring_mRNA_project/output_files/kidney_paired_combination.csv")
```


```{r}
matx <- all_data

p1 <- matx %>% 
  ggplot(
    aes(
     Treatment,
        y=ID,
        fill=NES)) +
  geom_tile(colour ="black") + 
  geom_point(data = matx[matx$pvalue < 0.05,], shape=1, size = 1)+
   geom_point(data = matx[matx$p.adjust < 0.05,],shape=16, size = 1)+
   scale_fill_distiller(palette='RdBu', limit = c(-2,2))+
	theme(panel.background=element_rect(fill = "white",color='white'),
axis.text = element_text(size=8,color='black'),legend.text=element_text(size=8,color='black'),legend.title=element_text(size=8,color='black', face = "bold")) + labs(fill='NES\n')

p1<- p1+	ggtitle("GSEA of hallmark gene sets") +
  xlab("") + ylab("")+
theme(axis.text.y = element_text(size = 12,angle = 0, vjust = 0.5, hjust = 1),
        axis.text.x = element_text(size = 10, angle = 45,hjust = 1), panel.grid = element_blank(), text = element_text(size = 12, face = "bold"))+  theme(legend.key.size = unit(0.5, 'cm'))+coord_flip()

pdf("~/Desktop/Nanostring_mRNA_project/Plots/kidney_paired_combination.pdf", height = 6, width = 14, bg = "white")
p1
```
